/**
 * UserFormModal — Modal dialog for creating or editing a user.
 * Adapts its title and fields based on the `mode` prop ('create' | 'edit').
 */
import { useState, useEffect } from 'react'
import { HiOutlineX } from 'react-icons/hi'

const ROLES = [
  { value: 'employee', label: 'Employee' },
  { value: 'manager', label: 'Manager' },
  { value: 'admin', label: 'Admin' },
]

function UserFormModal({ mode = 'create', user = null, currentUser = null, onClose, onSubmit }) {
  const isEdit = mode === 'edit'
  const isManager = currentUser?.role === 'manager'

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    team_id: isManager ? currentUser?.team_id || '' : '',
    role: 'employee',
  })
  const [errors, setErrors] = useState({})
  const [isLoading, setIsLoading] = useState(false)

  // Populate form when editing or initialize
  useEffect(() => {
    if (isEdit && user) {
      setFormData({
        name: user.name || '',
        email: user.email || '',
        password: '',
        team_id: user.team_id || (isManager ? currentUser?.team_id || '' : ''),
        role: user.role || 'employee',
      })
    } else if (isManager) {
      setFormData((prev) => ({
        ...prev,
        team_id: currentUser?.team_id || '',
        role: 'employee',
      }))
    }
  }, [isEdit, user, isManager, currentUser])

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))
    // Clear field error on change
    if (errors[name]) {
      setErrors((prev) => ({ ...prev, [name]: '' }))
    }
  }

  const validate = () => {
    const errs = {}
    if (!formData.name.trim()) errs.name = 'Name is required'
    if (!formData.email.trim()) errs.email = 'Email is required'
    else if (!/\S+@\S+\.\S+/.test(formData.email)) errs.email = 'Invalid email format'
    
    // For manager creating employee, password is optional (auto-generated by backend if empty)
    if (!isManager) {
      if (!isEdit && (!formData.password || formData.password.length < 6)) {
        errs.password = 'Password must be at least 6 characters'
      }
    }
    if (formData.password && formData.password.length < 6) {
      errs.password = 'Password must be at least 6 characters'
    }
    return errs
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    const errs = validate()
    if (Object.keys(errs).length) {
      setErrors(errs)
      return
    }

    setIsLoading(true)
    try {
      // Build payload — omit empty password on edit
      const payload = {
        name: formData.name.trim(),
        email: formData.email.trim().toLowerCase(),
        team_id: (isManager ? currentUser?.team_id : formData.team_id.trim().toUpperCase()) || null,
        role: isManager ? 'employee' : formData.role,
      }
      if (formData.password) {
        payload.password = formData.password
      }
      await onSubmit(payload)
    } catch (err) {
      const msg = err.response?.data?.error || 'Operation failed'
      setErrors({ form: msg })
    } finally {
      setIsLoading(false)
    }
  }

  // Close on Escape key
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content animate-slide-up" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <div>
            <h2 className="modal-title">
              {isEdit ? 'Edit User' : isManager ? 'Add Employee to Team' : 'Create User'}
            </h2>
            {isManager && (
              <p style={{ fontSize: '0.8rem', color: 'var(--color-text-secondary)', marginTop: '4px' }}>
                Authorize employee to access Team <strong>{currentUser?.team_id}</strong> workspace
              </p>
            )}
          </div>
          <button className="modal-close" onClick={onClose}>
            <HiOutlineX />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          {errors.form && (
            <div className="form-error" style={{ marginBottom: 'var(--space-4)', fontSize: 'var(--font-size-sm)' }}>
              {errors.form}
            </div>
          )}

          {/* Name */}
          <div className="form-group" style={{ marginBottom: 'var(--space-4)' }}>
            <label className="form-label" htmlFor="user-name">Employee Full Name</label>
            <input
              id="user-name"
              name="name"
              type="text"
              className="form-input"
              placeholder="Alex Mercer"
              value={formData.name}
              onChange={handleChange}
              autoFocus
            />
            {errors.name && <span className="form-error">{errors.name}</span>}
          </div>

          {/* Email */}
          <div className="form-group" style={{ marginBottom: 'var(--space-4)' }}>
            <label className="form-label" htmlFor="user-email">Employee Email Address</label>
            <input
              id="user-email"
              name="email"
              type="email"
              className="form-input"
              placeholder="alex@company.com"
              value={formData.email}
              onChange={handleChange}
            />
            {errors.email && <span className="form-error">{errors.email}</span>}
          </div>

          {/* Password (For Admin or general user management only) */}
          {!isManager && (
            <div className="form-group" style={{ marginBottom: 'var(--space-4)' }}>
              <label className="form-label" htmlFor="user-password">
                Password{isEdit ? ' (leave blank to keep unchanged)' : ''}
              </label>
              <input
                id="user-password"
                name="password"
                type="password"
                className="form-input"
                placeholder={isEdit ? '••••••••' : 'Min 6 characters'}
                value={formData.password}
                onChange={handleChange}
              />
              {errors.password && <span className="form-error">{errors.password}</span>}
            </div>
          )}

          {/* Team ID & Role for Admin only */}
          {!isManager && (
            <>
              {/* Team ID */}
              <div className="form-group" style={{ marginBottom: 'var(--space-4)' }}>
                <label className="form-label" htmlFor="user-team">Team ID / Code</label>
                <input
                  id="user-team"
                  name="team_id"
                  type="text"
                  className="form-input"
                  placeholder="e.g. TEAM-ALPHA, DEV-01"
                  value={formData.team_id}
                  onChange={handleChange}
                />
              </div>

              {/* Role */}
              <div className="form-group" style={{ marginBottom: 'var(--space-6)' }}>
                <label className="form-label" htmlFor="user-role">Role</label>
                <select
                  id="user-role"
                  name="role"
                  className="form-select"
                  value={formData.role}
                  onChange={handleChange}
                >
                  {ROLES.map((r) => (
                    <option key={r.value} value={r.value}>{r.label}</option>
                  ))}
                </select>
              </div>
            </>
          )}

          {isManager && (
            <div
              style={{
                marginBottom: 'var(--space-5)',
                padding: '10px 14px',
                background: 'var(--color-bg-primary)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                fontSize: '0.82rem',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <span>Target Workspace:</span>
              <span className="badge badge-violet">{currentUser?.team_id || 'YOUR-TEAM'}</span>
            </div>
          )}

          {/* Actions */}
          <div className="modal-actions">
            <button type="button" className="btn btn-secondary" onClick={onClose} disabled={isLoading}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary" disabled={isLoading}>
              {isLoading
                ? (isEdit ? 'Saving...' : 'Adding...')
                : (isEdit ? 'Save Changes' : isManager ? 'Add Employee' : 'Create User')
              }
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

export default UserFormModal
